functionsDirectory = "/Users/steveshearman/CascadeProjects/dtp_website2/company-website/netlify/functions"
functionsDirectoryOrigin = "config-v1"
headersOrigin = "config"
redirectsOrigin = "config"
plugins = []

[functions]

[functions."*"]

[build]
publish = "/Users/steveshearman/CascadeProjects/dtp_website2/company-website/dist"
publishOrigin = "config"
commandOrigin = "config"
command = "npm install && npm run build"
base = "/Users/steveshearman/CascadeProjects/dtp_website2/company-website"
functions = "/Users/steveshearman/CascadeProjects/dtp_website2/company-website/netlify/functions"

[build.environment]
NODE_VERSION = "18"
NPM_VERSION = "9"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[headers]]
for = "/*"

[headers.values]
Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
for = "/_astro/*"

[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/images/*"

[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/icons/*"

[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/fonts/*"

[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/home1"
to = "/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/news"
to = "/news2"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]